#! /bin/sh

# default config
#pgrep -x sxhkd > /dev/null || sxhkd &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# new config
# set root pointer
xsetroot -cursor_name left_ptr

# keyboard
setxkbmap us &

# monitor setup
xrandr --output eDP-1 --primary --mode 1366x768 --pos 1920x312 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal

#picom pkill picom
picom -b &
#picom --expiremental-backends --no-use-damage &

# key bindings
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &

# panel
$HOME/.config/polybar/launch.sh &

# set some bsp specific
bspc monitor HDMI-1 -d 一 二 三 四 五 六
bspc monitor eDP-1 -d 七 八 九 十

bspc config window_gap 8
bspc config border_width 1

bspc config focused_border_color "#acacac"
bspc config normal_border_color "#FF4a4a4a"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# wallpaper
$HOME/.fehbg
